# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(948, 338)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.price_min = QtWidgets.QLineEdit(Dialog)
        self.price_min.setMinimumSize(QtCore.QSize(145, 33))
        self.price_min.setMaximumSize(QtCore.QSize(145, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.price_min.setFont(font)
        self.price_min.setObjectName("price_min")
        self.horizontalLayout.addWidget(self.price_min)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setMinimumSize(QtCore.QSize(16, 33))
        self.label_16.setMaximumSize(QtCore.QSize(16, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.price_max = QtWidgets.QLineEdit(Dialog)
        self.price_max.setMinimumSize(QtCore.QSize(145, 33))
        self.price_max.setMaximumSize(QtCore.QSize(145, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.price_max.setFont(font)
        self.price_max.setObjectName("price_max")
        self.horizontalLayout.addWidget(self.price_max)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.purchase_date_chk = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.purchase_date_chk.setFont(font)
        self.purchase_date_chk.setText("")
        self.purchase_date_chk.setObjectName("purchase_date_chk")
        self.horizontalLayout_2.addWidget(self.purchase_date_chk)
        self.purchase_date_min = QtWidgets.QDateEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.purchase_date_min.setFont(font)
        self.purchase_date_min.setCalendarPopup(True)
        self.purchase_date_min.setObjectName("purchase_date_min")
        self.horizontalLayout_2.addWidget(self.purchase_date_min)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(16, 33))
        self.label_8.setMaximumSize(QtCore.QSize(16, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.purchase_date_max = QtWidgets.QDateEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.purchase_date_max.setFont(font)
        self.purchase_date_max.setCalendarPopup(True)
        self.purchase_date_max.setObjectName("purchase_date_max")
        self.horizontalLayout_2.addWidget(self.purchase_date_max)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 1, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.acquire_date_chk = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.acquire_date_chk.setFont(font)
        self.acquire_date_chk.setText("")
        self.acquire_date_chk.setObjectName("acquire_date_chk")
        self.horizontalLayout_3.addWidget(self.acquire_date_chk)
        self.acquire_date_min = QtWidgets.QDateEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.acquire_date_min.setFont(font)
        self.acquire_date_min.setCalendarPopup(True)
        self.acquire_date_min.setObjectName("acquire_date_min")
        self.horizontalLayout_3.addWidget(self.acquire_date_min)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMinimumSize(QtCore.QSize(16, 33))
        self.label_9.setMaximumSize(QtCore.QSize(16, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.acquire_date_max = QtWidgets.QDateEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.acquire_date_max.setFont(font)
        self.acquire_date_max.setCalendarPopup(True)
        self.acquire_date_max.setObjectName("acquire_date_max")
        self.horizontalLayout_3.addWidget(self.acquire_date_max)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.subcategory = QtWidgets.QComboBox(Dialog)
        self.subcategory.setMinimumSize(QtCore.QSize(350, 33))
        self.subcategory.setMaximumSize(QtCore.QSize(350, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.subcategory.setFont(font)
        self.subcategory.setEditable(True)
        self.subcategory.setObjectName("subcategory")
        self.gridLayout_2.addWidget(self.subcategory, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.brand = QtWidgets.QComboBox(Dialog)
        self.brand.setMinimumSize(QtCore.QSize(350, 33))
        self.brand.setMaximumSize(QtCore.QSize(350, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.brand.setFont(font)
        self.brand.setEditable(True)
        self.brand.setObjectName("brand")
        self.gridLayout_2.addWidget(self.brand, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.spec = QtWidgets.QComboBox(Dialog)
        self.spec.setMinimumSize(QtCore.QSize(350, 33))
        self.spec.setMaximumSize(QtCore.QSize(350, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.spec.setFont(font)
        self.spec.setEditable(True)
        self.spec.setObjectName("spec")
        self.gridLayout_2.addWidget(self.spec, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 2, 1, 1)
        self.name = QtWidgets.QComboBox(Dialog)
        self.name.setMinimumSize(QtCore.QSize(350, 33))
        self.name.setMaximumSize(QtCore.QSize(350, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.name.setFont(font)
        self.name.setEditable(True)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 1, 1, 1, 1)
        self.category = QtWidgets.QComboBox(Dialog)
        self.category.setMinimumSize(QtCore.QSize(350, 33))
        self.category.setMaximumSize(QtCore.QSize(350, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.category.setFont(font)
        self.category.setEditable(True)
        self.category.setObjectName("category")
        self.gridLayout_2.addWidget(self.category, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 2, 1, 1)
        self.place = QtWidgets.QComboBox(Dialog)
        self.place.setMinimumSize(QtCore.QSize(350, 33))
        self.place.setMaximumSize(QtCore.QSize(350, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.place.setFont(font)
        self.place.setEditable(True)
        self.place.setObjectName("place")
        self.gridLayout_2.addWidget(self.place, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.keep_department = QtWidgets.QComboBox(Dialog)
        self.keep_department.setMinimumSize(QtCore.QSize(350, 33))
        self.keep_department.setMaximumSize(QtCore.QSize(350, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.keep_department.setFont(font)
        self.keep_department.setEditable(True)
        self.keep_department.setObjectName("keep_department")
        self.gridLayout_2.addWidget(self.keep_department, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.use_department = QtWidgets.QComboBox(Dialog)
        self.use_department.setMinimumSize(QtCore.QSize(350, 33))
        self.use_department.setMaximumSize(QtCore.QSize(350, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.use_department.setFont(font)
        self.use_department.setEditable(True)
        self.use_department.setObjectName("use_department")
        self.gridLayout_2.addWidget(self.use_department, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.keeper = QtWidgets.QComboBox(Dialog)
        self.keeper.setMinimumSize(QtCore.QSize(350, 33))
        self.keeper.setMaximumSize(QtCore.QSize(350, 33))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.keeper.setFont(font)
        self.keeper.setEditable(True)
        self.keeper.setObjectName("keeper")
        self.gridLayout_2.addWidget(self.keeper, 6, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 6, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setAutoDefault(False)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_4.addWidget(self.cancelBtn)
        self.submitBtn = QtWidgets.QPushButton(Dialog)
        self.submitBtn.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.submitBtn.setFont(font)
        self.submitBtn.setDefault(True)
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout_4.addWidget(self.submitBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        self.cancelBtn.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.category, self.subcategory)
        Dialog.setTabOrder(self.subcategory, self.name)
        Dialog.setTabOrder(self.name, self.brand)
        Dialog.setTabOrder(self.brand, self.spec)
        Dialog.setTabOrder(self.spec, self.price_min)
        Dialog.setTabOrder(self.price_min, self.price_max)
        Dialog.setTabOrder(self.price_max, self.purchase_date_chk)
        Dialog.setTabOrder(self.purchase_date_chk, self.purchase_date_min)
        Dialog.setTabOrder(self.purchase_date_min, self.purchase_date_max)
        Dialog.setTabOrder(self.purchase_date_max, self.acquire_date_chk)
        Dialog.setTabOrder(self.acquire_date_chk, self.acquire_date_min)
        Dialog.setTabOrder(self.acquire_date_min, self.acquire_date_max)
        Dialog.setTabOrder(self.acquire_date_max, self.place)
        Dialog.setTabOrder(self.place, self.keep_department)
        Dialog.setTabOrder(self.keep_department, self.use_department)
        Dialog.setTabOrder(self.use_department, self.keeper)
        Dialog.setTabOrder(self.keeper, self.cancelBtn)
        Dialog.setTabOrder(self.cancelBtn, self.submitBtn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "請設定資料過濾條件"))
        self.label_16.setText(_translate("Dialog", "~"))
        self.label_8.setText(_translate("Dialog", "~"))
        self.label_9.setText(_translate("Dialog", "~"))
        self.label_11.setText(_translate("Dialog", "品牌："))
        self.label.setText(_translate("Dialog", "物品大類："))
        self.label_4.setText(_translate("Dialog", "物品名稱："))
        self.label_3.setText(_translate("Dialog", "規格："))
        self.label_12.setText(_translate("Dialog", "單價："))
        self.label_10.setText(_translate("Dialog", "物品細目："))
        self.label_5.setText(_translate("Dialog", "取得日期："))
        self.label_13.setText(_translate("Dialog", "存置地點："))
        self.label_6.setText(_translate("Dialog", "保管單位："))
        self.label_7.setText(_translate("Dialog", "使用單位："))
        self.label_2.setText(_translate("Dialog", "購置日期："))
        self.label_14.setText(_translate("Dialog", "保管人："))
        self.cancelBtn.setText(_translate("Dialog", "取消"))
        self.submitBtn.setText(_translate("Dialog", "確定"))

